name: CI - Producao 

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  producao-ci: 
    name: "Run Tests + SonarCloud"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          if [ -f .docker/bin/config/requirements.txt ]; then
            pip install -r .docker/bin/config/requirements.txt
          else
            echo "Arquivo .docker/bin/config/requirements.txt n√£o encontrado."
            exit 1
          fi
          pip install pytest pytest-cov

      - name: Run tests
        env:
          PYTHONPATH: .
        run: |
          if [ -d app/tests ]; then
            python -m pytest app/tests --cov=app --cov-report=xml:app/coverage.xml
          else
            echo "Nenhuma pasta de testes encontrada, pulando."
          fi

      - name: SonarCloud Scan
        if: always()
        uses: sonarsource/sonarcloud-github-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_GB }}
        with:
          projectBaseDir: .